//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiShop.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SushiShop.Core.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SelectSity {
            get {
                return ResourceManager.GetString("SelectSity", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string SearchSity {
            get {
                return ResourceManager.GetString("SearchSity", resourceCulture);
            }
        }
        
        public static string Franchise {
            get {
                return ResourceManager.GetString("Franchise", resourceCulture);
            }
        }
        
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        public static string GoToTheFranchisePage {
            get {
                return ResourceManager.GetString("GoToTheFranchisePage", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string PublicOffer {
            get {
                return ResourceManager.GetString("PublicOffer", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string IsItYourCityQuestionTemplate {
            get {
                return ResourceManager.GetString("IsItYourCityQuestionTemplate", resourceCulture);
            }
        }
        
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        public static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        public static string Ccal {
            get {
                return ResourceManager.GetString("Ccal", resourceCulture);
            }
        }
        
        public static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        public static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string MakeItTastier {
            get {
                return ResourceManager.GetString("MakeItTastier", resourceCulture);
            }
        }
        
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        public static string AddSauce {
            get {
                return ResourceManager.GetString("AddSauce", resourceCulture);
            }
        }
        
        public static string PromocodeApplied {
            get {
                return ResourceManager.GetString("PromocodeApplied", resourceCulture);
            }
        }
        
        public static string Promocode {
            get {
                return ResourceManager.GetString("Promocode", resourceCulture);
            }
        }
        
        public static string GramSymbol {
            get {
                return ResourceManager.GetString("GramSymbol", resourceCulture);
            }
        }
        
        public static string MillilitersSymbol {
            get {
                return ResourceManager.GetString("MillilitersSymbol", resourceCulture);
            }
        }
        
        public static string FromToDateFormat {
            get {
                return ResourceManager.GetString("FromToDateFormat", resourceCulture);
            }
        }
        
        public static string FromDateFormat {
            get {
                return ResourceManager.GetString("FromDateFormat", resourceCulture);
            }
        }
        
        public static string AnswerDeleteItemFromBasket {
            get {
                return ResourceManager.GetString("AnswerDeleteItemFromBasket", resourceCulture);
            }
        }
        
        public static string CountInPC {
            get {
                return ResourceManager.GetString("CountInPC", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string ProfileLoginPlaceholder {
            get {
                return ResourceManager.GetString("ProfileLoginPlaceholder", resourceCulture);
            }
        }
        
        public static string AcceptPhoneTitle {
            get {
                return ResourceManager.GetString("AcceptPhoneTitle", resourceCulture);
            }
        }
        
        public static string LastFourDigits {
            get {
                return ResourceManager.GetString("LastFourDigits", resourceCulture);
            }
        }
        
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        public static string NameAndSurnameRequired {
            get {
                return ResourceManager.GetString("NameAndSurnameRequired", resourceCulture);
            }
        }
        
        public static string DateOfBirthRequired {
            get {
                return ResourceManager.GetString("DateOfBirthRequired", resourceCulture);
            }
        }
        
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
    }
}
