//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiShop.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SushiShop.Core.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string SearchCity {
            get {
                return ResourceManager.GetString("SearchCity", resourceCulture);
            }
        }
        
        public static string Franchise {
            get {
                return ResourceManager.GetString("Franchise", resourceCulture);
            }
        }
        
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        public static string GoToTheFranchisePage {
            get {
                return ResourceManager.GetString("GoToTheFranchisePage", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyConfirmation {
            get {
                return ResourceManager.GetString("PrivacyPolicyConfirmation", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string PublicOffer {
            get {
                return ResourceManager.GetString("PublicOffer", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string IsItYourCityQuestionTemplate {
            get {
                return ResourceManager.GetString("IsItYourCityQuestionTemplate", resourceCulture);
            }
        }
        
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        public static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        public static string Ccal {
            get {
                return ResourceManager.GetString("Ccal", resourceCulture);
            }
        }
        
        public static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        public static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string MakeItTastier {
            get {
                return ResourceManager.GetString("MakeItTastier", resourceCulture);
            }
        }
        
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        public static string AddSauce {
            get {
                return ResourceManager.GetString("AddSauce", resourceCulture);
            }
        }
        
        public static string PromocodeApplied {
            get {
                return ResourceManager.GetString("PromocodeApplied", resourceCulture);
            }
        }
        
        public static string Promocode {
            get {
                return ResourceManager.GetString("Promocode", resourceCulture);
            }
        }
        
        public static string GramSymbol {
            get {
                return ResourceManager.GetString("GramSymbol", resourceCulture);
            }
        }
        
        public static string MillilitersSymbol {
            get {
                return ResourceManager.GetString("MillilitersSymbol", resourceCulture);
            }
        }
        
        public static string FromToDateFormat {
            get {
                return ResourceManager.GetString("FromToDateFormat", resourceCulture);
            }
        }
        
        public static string FromDateFormat {
            get {
                return ResourceManager.GetString("FromDateFormat", resourceCulture);
            }
        }
        
        public static string AnswerDeleteItemFromBasket {
            get {
                return ResourceManager.GetString("AnswerDeleteItemFromBasket", resourceCulture);
            }
        }
        
        public static string CountInPC {
            get {
                return ResourceManager.GetString("CountInPC", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string OrderTemplate {
            get {
                return ResourceManager.GetString("OrderTemplate", resourceCulture);
            }
        }
        
        public static string ProfileLoginPlaceholder {
            get {
                return ResourceManager.GetString("ProfileLoginPlaceholder", resourceCulture);
            }
        }
        
        public static string AcceptPhoneTitle {
            get {
                return ResourceManager.GetString("AcceptPhoneTitle", resourceCulture);
            }
        }
        
        public static string LastFourDigits {
            get {
                return ResourceManager.GetString("LastFourDigits", resourceCulture);
            }
        }
        
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        public static string NameAndSurnameRequired {
            get {
                return ResourceManager.GetString("NameAndSurnameRequired", resourceCulture);
            }
        }
        
        public static string DateOfBirthRequired {
            get {
                return ResourceManager.GetString("DateOfBirthRequired", resourceCulture);
            }
        }
        
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        public static string RepeatOrder {
            get {
                return ResourceManager.GetString("RepeatOrder", resourceCulture);
            }
        }
        
        public static string OrderComposition {
            get {
                return ResourceManager.GetString("OrderComposition", resourceCulture);
            }
        }
        
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string PreferredDeliveryTime {
            get {
                return ResourceManager.GetString("PreferredDeliveryTime", resourceCulture);
            }
        }
        
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string ReceiveMethod {
            get {
                return ResourceManager.GetString("ReceiveMethod", resourceCulture);
            }
        }
        
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string UploadPhotos {
            get {
                return ResourceManager.GetString("UploadPhotos", resourceCulture);
            }
        }
        
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        public static string UploadFromGallery {
            get {
                return ResourceManager.GetString("UploadFromGallery", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string SignOutOfYourProfile {
            get {
                return ResourceManager.GetString("SignOutOfYourProfile", resourceCulture);
            }
        }
        
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        public static string Pickup {
            get {
                return ResourceManager.GetString("Pickup", resourceCulture);
            }
        }
        
        public static string FreeOfCharge {
            get {
                return ResourceManager.GetString("FreeOfCharge", resourceCulture);
            }
        }
        
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        public static string Shops {
            get {
                return ResourceManager.GetString("Shops", resourceCulture);
            }
        }
        
        public static string Metro {
            get {
                return ResourceManager.GetString("Metro", resourceCulture);
            }
        }
        
        public static string OnMap {
            get {
                return ResourceManager.GetString("OnMap", resourceCulture);
            }
        }
        
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        public static string NoNearestMetro {
            get {
                return ResourceManager.GetString("NoNearestMetro", resourceCulture);
            }
        }
        
        public static string DriveWay {
            get {
                return ResourceManager.GetString("DriveWay", resourceCulture);
            }
        }
        
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        public static string ReceiveInShop {
            get {
                return ResourceManager.GetString("ReceiveInShop", resourceCulture);
            }
        }
        
        public static string СourierDelivery {
            get {
                return ResourceManager.GetString("СourierDelivery", resourceCulture);
            }
        }
        
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        public static string OrderPayment {
            get {
                return ResourceManager.GetString("OrderPayment", resourceCulture);
            }
        }
        
        public static string OrderRegistrationTitle {
            get {
                return ResourceManager.GetString("OrderRegistrationTitle", resourceCulture);
            }
        }
        
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        public static string Intercom {
            get {
                return ResourceManager.GetString("Intercom", resourceCulture);
            }
        }
        
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        public static string SelectOrderDeliveryTitle {
            get {
                return ResourceManager.GetString("SelectOrderDeliveryTitle", resourceCulture);
            }
        }
        
        public static string EnterYourAddress {
            get {
                return ResourceManager.GetString("EnterYourAddress", resourceCulture);
            }
        }
        
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        public static string PriceOfDelivery {
            get {
                return ResourceManager.GetString("PriceOfDelivery", resourceCulture);
            }
        }
        
        public static string PickDeliveryAddress {
            get {
                return ResourceManager.GetString("PickDeliveryAddress", resourceCulture);
            }
        }
        
        public static string ShopAddress {
            get {
                return ResourceManager.GetString("ShopAddress", resourceCulture);
            }
        }
        
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        public static string UserAgreement {
            get {
                return ResourceManager.GetString("UserAgreement", resourceCulture);
            }
        }
        
        public static string ReceiveTimeTemplate {
            get {
                return ResourceManager.GetString("ReceiveTimeTemplate", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyConfirmOrder {
            get {
                return ResourceManager.GetString("PrivacyPolicyConfirmOrder", resourceCulture);
            }
        }
        
        public static string ThanksForFeedback {
            get {
                return ResourceManager.GetString("ThanksForFeedback", resourceCulture);
            }
        }
        
        public static string SelectShop {
            get {
                return ResourceManager.GetString("SelectShop", resourceCulture);
            }
        }
        
        public static string DevelopedAt {
            get {
                return ResourceManager.GetString("DevelopedAt", resourceCulture);
            }
        }
        
        public static string BuyWithThisProduct {
            get {
                return ResourceManager.GetString("BuyWithThisProduct", resourceCulture);
            }
        }
        
        public static string DoYouLikeSushiShopApp {
            get {
                return ResourceManager.GetString("DoYouLikeSushiShopApp", resourceCulture);
            }
        }
        
        public static string FeedbackFrom {
            get {
                return ResourceManager.GetString("FeedbackFrom", resourceCulture);
            }
        }
        
        public static string ChoosePackage {
            get {
                return ResourceManager.GetString("ChoosePackage", resourceCulture);
            }
        }
        
        public static string CheckoutOrder {
            get {
                return ResourceManager.GetString("CheckoutOrder", resourceCulture);
            }
        }
        
        public static string EmptyCart {
            get {
                return ResourceManager.GetString("EmptyCart", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        public static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        public static string SmsNotifications {
            get {
                return ResourceManager.GetString("SmsNotifications", resourceCulture);
            }
        }
        
        public static string ReceiveNotificationsAboutNewsAndPromotions {
            get {
                return ResourceManager.GetString("ReceiveNotificationsAboutNewsAndPromotions", resourceCulture);
            }
        }
        
        public static string NearestMetroStation {
            get {
                return ResourceManager.GetString("NearestMetroStation", resourceCulture);
            }
        }
        
        public static string PickAt {
            get {
                return ResourceManager.GetString("PickAt", resourceCulture);
            }
        }
        
        public static string DevicesCount {
            get {
                return ResourceManager.GetString("DevicesCount", resourceCulture);
            }
        }
        
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        public static string OnPickup {
            get {
                return ResourceManager.GetString("OnPickup", resourceCulture);
            }
        }
        
        public static string CashPaymentDescription {
            get {
                return ResourceManager.GetString("CashPaymentDescription", resourceCulture);
            }
        }
        
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        public static string OnlinePaymentDescription {
            get {
                return ResourceManager.GetString("OnlinePaymentDescription", resourceCulture);
            }
        }
        
        public static string DiscountByPromocode {
            get {
                return ResourceManager.GetString("DiscountByPromocode", resourceCulture);
            }
        }
        
        public static string DiscountByCard {
            get {
                return ResourceManager.GetString("DiscountByCard", resourceCulture);
            }
        }
        
        public static string AppliedScores {
            get {
                return ResourceManager.GetString("AppliedScores", resourceCulture);
            }
        }
    }
}
